steps:
  # Build da imagem Docker SEM CACHE
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '--tag'
      - 'gcr.io/$PROJECT_ID/monpec:latest'
      - '--file'
      - 'Dockerfile.prod'
      - '.'
  
  # Push da imagem para Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/monpec:latest'

images:
  - 'gcr.io/$PROJECT_ID/monpec:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'








